version: "3.3"
services:
    nodeserver:
        build:
            context: ./web
        ports:
            - "127.0.0.1:8000:8000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8800:80"
